POST https://crud-node-video.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET https://crud-node-video.onrender.com/videos

###

PUT https://crud-node-video.onrender.com/videos/ea2f6555-4d6f-477b-92d2-2f626c883caa
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://crud-node-video.onrender.com/videos/ea2f6555-4d6f-477b-92d2-2f626c883caa